export const SAVE_USER_CHOICE="SAVE_USER_CHOICE";
export const SAVE_SINGLE_USER_CHOICE="REMOVE_ALL_USER_CHOICE";
//SECOND REDUCER
export const CHANGE_CURRENT_Q="CHANGE_CURRENT_Q";
export const CHANGE_MODAL_STATUS="CHANGE_MODAL_STATUS";
export const SET_BOOKMARK="SET_BOOKMARK";

//AUTHENTICATION
export const SET_USER="SET_USER";
export const REMOVE_USER="REMOVE_USER";

//SET STATES
export const SET_INITIAL_STATE="SET_INITIAL_STATE";
export const SET_QUESTIONS="SET_QUESTIONS"