export const SAVE_USER_CHOICE="SAVE_USER_CHOICE";

//SECOND REDUCER
export const CHANGE_CURRENT_Q="CHANGE_CURRENT_Q";
export const CHANGE_MODAL_STATUS="CHANGE_MODAL_STATUS";

//AUTHENTICATION
export const SET_USER="SET_USER";
export const REMOVE_USER="REMOVE_USER";